const statusCode = {
    ok: 200,
    unauth: 401,
    notFound: 404,
    validation: 400,
    failed: 1002,
    invalidURL: 1001,
    paymentReq: 402,
    internalError: 1004,
    forbidden: 403,
    internalservererror: 500,
    alreadyExist: 409, //conflict
  }

  const cryptoConfig = {
    cryptoAlgorithm: 'aes-256-ctr',
    cryptoPassword: 'd6F3Efeq',
    secret: 'p-rfct@2020',
  }
  const messages = {
    reminder_send: 'Reminder send successfully',
    // subs_feature: 'Subscription plan feature is required',
    profileUpdateSuccess: 'Profile updated successfully.',
    title: 'Title is required',
    IMG_DELETED: 'File deleted successfully.',
    description: ' Description is required.',
    userId: 'User ID is required.',
    image_upl: 'Image uploaded successfully',
    // faqID: 'ID is required.',
    SIZE_EXCEEDED: 'Image should not greater then 5 mb in size.',
    INVALID_IMAGE: 'Only jpeg,png file format are allowed.',
    INVALID_VIDEO: 'Only mp4 and MPEG-2 file format are allowed.',
    NOT_UPLOADED: 'Image not uploaded',
    commonError: 'Something went wrong',
    loginSuccess: 'Logged in successfully',
    signupSuccess:
      'Signup successfully',
    // invitationSuccess: 'Invitation sent successfully.',
    ccountUpdated: 'Your account updated successfully.',
    loginOut: 'Logout successfully',
    Registration: 'You have successfully registered',
    emailAlreadyExist: 'Email already exist',
    newAndoldPwdNotMatch: 'Password not match',
    cardholder: 'Name is required.',
    // subscription_amount: 'Subscription amount is required.',
    // card_number: 'Card number is required.',
    forgotPasswordSuccess: 'Reset password link sent to your email',
    createPasswordSuccess: 'Password created successfully.',
    AddCartSuccess:'Product added in cart  successfully',
    removeCartSuccess:'Product delete in cart  successfully',
    alreadyInCart:'Product already in your cart',
    validUrl: 'Valid Url',
    invalidUrl: 'Invalid Url',
    registration_user: 'User name is required.',
    registration_email: 'Email  is required.',
    registration_password: 'Password  is required.',
    registration_con_password: 'Confirm password  is required.',
    registration_firm_number: 'Firm number  is required.',
    registration_location: 'Location is required',
    registration_company_name: 'Company name is required.',
    registration_sign_up: 'Sign up type  is required.',
    first_name: 'First name is required',
    mobile_no: 'Contact number is required.',
    businessType: 'Account type is required.',
    last_name: 'Last name is required',
    // city: 'City is required',
    // state: 'State is required',
    // zip: 'Zipcode is required',
    // address: 'Address is required',
    mobileNoRiq: 'Mobile number is required',
    ExecutedSuccessfully: 'Data fetched successfully.',
    updated_successfully: 'Data updated successfully.',
    NoDataFound: 'No Data Found',
    deleted: 'Deleted successfully.',
    invalidTransaction: 'Transaction failed due to ',
    user_signup_fail: 'User not added.',
    roleNameErrorMsg : "Please add the role name",
    internalservererror:"Internal server error",
    userNotFound:"User not Found",
    accountNotActive:"This account is not active",
    accountdeleted:"This account has been deleted",
    deActivated:"Deactivated successfully",
    activated:"Activated successfully",
    requiredFieldsMissing:"All Field are required",
    noRecordFound: 'No data found',
    delSuccess:'Record deleted successfully',
    userCreate: "User created successfully",
    invitationSend: 'Invitation sent successfully',
    registerButEmailNotSend: 'User are register but invitation mail is not sent ',
    userDataUpdated: "User Information updated successfully",
    AdminProfileUpdate:"Admin profile updated successfully",
    oldPswdReq:"Old password required",
    newPswdReq: "New password required",
    confirmPswdReq : "Confirm password required",
    confirmPswdNotMatch : "New password and confirm password did not match",
    newAndoldPwdNotSame : "New password and old password are same",
    wrongOldPswd:"New password and old password same",
    pswdChangeSuccess: "Password changed successfully",
    incorrectEmail:"Email id dose not exits",
    accountNotActive : "Account is not activated, Please activate the account",
    accountdeleted: "Account are deleted",
    emailNotSend:"Email  not sent",
    tokenExpire: "Token has expired",
    token:"Token is required",
    addressNotExitAndSave:'Customer address is not exist , But Now address is save ',
    addressUpdated:'Customer address is updated successfully',
    orderCreatedSuccess :'Order created  successfully',
    storiesSuccess : "Stories is created successfully",
    ActiveStoriesStatusChange :"Stories activated  successfully",
    DeActiveStoriesStatusChange :"Stories deActivated successfully",
  }
  
  const resetPassword_message = {
    key_password_required: 'Reset key or password is missing.',
    reset_token_expire:
      'Reset password token expired! Regenerate token to set password',
    password_reset_success: 'Password reset successfully.Please try to login.',
    noExitToken:'This is token is not exits, please check the mail and try with latest mail'
  }
  const validateMsg = {
    successfullyExecuted: 'Successfully executed..',
    notSupportedType: 'Format not supported',
    generalValidationMessage: 'There are one or more validation errors.',
    emailAlreadyExist: 'Email Id already exist, try with another',
    passwordDoNotUseSame: 'New password should not be same as old password',
    //Account
    accountIsNotActive: 'Your account is not Activated.',
    //User
    invalidOldPassword: 'Old password in not correct.',
    userIdRequired: 'User Id is required',
    usernameAlreadyExist: 'Username already exist, try with another',
    emailRequired: 'Email is required',
    firstnameRequired: 'First name is required',
    passwordRequired: 'Password is required',
    DOBRequired:'Date of birth is required',
    preferenceRequired:'Shopping preference is required',
    deviceTypeRequired: 'Device type is required',
    deviceIdRequired: 'Device id is required',
    deviceTokenRequired: 'Device token is required',
    invalidEmail: 'Invalid Email Given',
    invalidEmailOrPassword: 'Invalid email or password',
    VALIDOTP: 'OTP or user is missing',
    INVALIDOTP: 'Invalid OTP.Please try again with logging process.',
    INVALIDOTP1: 'Invalid OTP.Please enter valid OTP.',
    OTPMESSAGE: 'An OTP is sent to your registered email address.',
    internalError: 'Internal error -----',
    requiredFieldsMissing: 'Required fields missing',
    atleastoneCheck: 'Select minimum one Permission',
    emailNotExist: "Email doesn't exist",
    userNotFound: 'User not found',
    passwordNotMatch: 'New password should not be same as old password',
    invalidDeviceType: 'Invalid device type, It should be Android or iOS',
    noRecordFound: 'No record found',
    emailNotSent: 'Email not Sent',
    noDataInCart: 'There on item in cart currently'
  
  }
  const userTypes = {
    admin: 'Admin',
  }

  const directoryPath = {
    USERIMAGE: '../truck-backend/uploads/user/',
    EVENTBANNER: '../truck-backend/uploads/event/banner/',
    EVENTIMAGE: '../truck-backend/uploads/event/image/',
    EVENTVIDEO: '../truck-backend/uploads/event/video/',
  }
  const obj = {
    statusCode: statusCode,
    messages: messages,
    validateMsg: validateMsg,
    cryptoConfig:cryptoConfig,
    resetPassword_message:resetPassword_message
  }
  module.exports = obj